# Ansible playbook to do a basic configuration on CentOS VMs
# -Updates Yum Packages
# -Installs specified packages
# -Installs CheckMK Agent RPM
# -Registers the Agent with CheckMK instance
# -Runs Service Discovery
# -Activates changes
#
# Syntax: 
#    ansible-playbook -i<targetIP>  main.yaml
# Example: 
#    ansible-playbook -i192.168.0.48  main.yaml
#


- hosts: all

  tasks:
    - name: update packages
      yum:
       name: '*'
       state: latest

    - name: install packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - epel-release
        - telnet
        - net-tools
        - bind-utils

    - name: Copy CheckMK agent RPM
      copy:
        src: /opt/ansible/sources/CheckMK/agents/check-mk-agent-1.6.0p11-1.noarch.rpm
        dest: /tmp/check-mk-agent-1.6.0p11-1.noarch.rpm
        owner: root
        group: root
        mode : '0776'

    - name: Register IP Address
      shell: hostname -I | cut -d ' ' -f 2
      register: ipAddress

    - name: Register hostname
      shell: /usr/bin/hostname
      register: hostname

    - name: Install CheckMK Agent RPM
      yum:
        name: /tmp/check-mk-agent-1.6.0p11-1.noarch.rpm
        state: present      

    - name: Create host in CheckMK
      shell: curl "http://192.168.0.80/monitoring/check_mk/webapi.py?action=add_host&_username=automation&_secret=VNKYBXORBSWAFMLJ@XLM" -d 'request={"hostname":"{{ hostname.stdout }}","folder":"","attributes":{"ipaddress":"{{ ipAddress.stdout }}","site":"monitoring"}}'

    - name: Execute Service Discovery on host in CheckMK
      shell: curl "http://192.168.0.80/monitoring/check_mk/webapi.py?action=discover_services&_username=automation&_secret=VNKYBXORBSWAFMLJ@XLM" -d 'request={"hostname":"{{ hostname.stdout }}"}'

    - name: Activate Changes in CheckMK
      shell: curl "http://192.168.0.80/monitoring/check_mk/webapi.py?action=activate_changes&_username=automation&_secret=VNKYBXORBSWAFMLJ@XLM" -d 'request={"sites":["monitoring"]}'
