# Ansible playbook to Install and Register a CheckMK Agent
# -Installs CheckMK Agent RPM
# -Registers the Agent with CheckMK instance
# -Runs Service Discovery
# -Activates changes
#
# Syntax:
#    ansible-playbook -i <path to inventory> -l <host group / hostname> <path to playbook>
#

- hosts: all
  remote_user: root
  become: yes
  become_method: sudo

  tasks:
    - name: Ensure CheckMK Agent RPM is present
      copy:
        src: /etc/ansible/sources/CheckMK/agents/check-mk-agent-1.6.0p11-1.noarch.rpm
        dest: /tmp/check-mk-agent-1.6.0p11-1.noarch.rpm
        owner: root
        group: root
        mode : '0776'

    - name: Register IP Address Variable
      shell: hostname -I | cut -d ' ' -f 2
      register: ipAddress

    - name: Register hostname Variable
      shell: /usr/bin/hostname
      register: hostname

    - name: Ensure CheckMK Agent RPM is installed
      yum:
        name: /tmp/check-mk-agent-1.6.0p11-1.noarch.rpm
        state: present

    - name: Create host in CheckMK
      shell: curl "http://192.168.0.80/monitoring/check_mk/webapi.py?action=add_host&_username=automation&_secret=VNKYBXORBSWAFMLJ@XLM" -d 'request={"hostname":"{{ hostname.stdout }}","folder":"","attributes":{"ipaddress":"{{ ipAddress.stdout }}","site":"monitoring"}}'
      register: create_host

    - name: Execute Service Discovery on host in CheckMK
      shell: curl "http://192.168.0.80/monitoring/check_mk/webapi.py?action=discover_services&_username=automation&_secret=VNKYBXORBSWAFMLJ@XLM" -d 'request={"hostname":"{{ hostname.stdout }}"}'
      register: service_discovery

    - name: Activate Changes in CheckMK
      shell: curl "http://192.168.0.80/monitoring/check_mk/webapi.py?action=activate_changes&_username=automation&_secret=VNKYBXORBSWAFMLJ@XLM" -d 'request={"sites":["monitoring"]}'
      register: activate_changes
